### ISSUE TITLE
Error after selecting Tools > Cross Profile Search and Import

### ISSUE THREAD

**Issue by tigecyclindamycin** [rsimmons/anki-cropro#5]
Debug info:
Anki 2.1.16 (2e7b7560) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Cross Profile Search and Import

Caught exception:
Traceback (most recent call last):
  File "/Users/***/Library/Application Support/Anki2/addons21/310394744/cropro.py", line 79, in __init__
    self.initUI()
  File "/Users/***/Library/Application Support/Anki2/addons21/310394744/cropro.py", line 89, in initUI
    self.handleSelectOtherProfile(otherProfileNames[0])
  File "/Users/***/Library/Application Support/Anki2/addons21/310394744/cropro.py", line 231, in handleSelectOtherProfile
    self.otherProfileCollection = openProfileCollection(name)
  File "/Users/***/Library/Application Support/Anki2/addons21/310394744/cropro.py", line 70, in openProfileCollection
    return Collection(collectionFilename)
  File "anki/storage.py", line 28, in Collection
  File "anki/db.py", line 14, in __init__
sqlite3.OperationalError: unable to open database file

**Comment by tigecyclindamycin** [comment]
Edit: the issue resolved magically after i deleted a bunch of add-ons (not sure which specific add-on is causing the trouble)
